# Active la console H2
spring.h2.console.enabled=true

# Autorise l'affichage de la console dans les frames (nécessaire pour H2)
spring.web.security.restrict-definer-header=false

# Configure le chemin de la console
spring.h2.console.path=/h2-console

spring.datasource.generate-unique-name=false